CC=gcc
CFLAGS=-I. -Wall -O3

all: mobility_server

mobility_server:
	$(CC) $(CFLAGS) -DMOBILITY_SERVER_CHECK_COMPROMISED_APPLICATION=0 mobility_server.c -o mobility_server

with_ra:
	$(CC) $(CFLAGS) mobility_server.c -o mobility_server -lmysqlclient

clean:
	rm -f mobility_server *.o mobile_dump_*
