CC=/opt/diablo-android-gcc-toolchain/bin/arm-linux-androideabi-gcc
CFLAGS=-O3 -fPIC -marm -mfloat-abi=softfp -msoft-float -mfpu=neon -std=gnu99 -Wall -Werror

all: downloader
	
downloader:
	$(CC) $(CFLAGS) -c downloader.c -o downloader.o

clean:
	rm -f *.o