CC=/opt/diablo-gcc-toolchain/bin/arm-diablo-linux-gnueabi-gcc
OPTIONS=-O3 -fPIC -marm -mfloat-abi=softfp -msoft-float -mfpu=neon -std=gnu99 -Wall

default:
	$(CC) $(OPTIONS) -o binder.o -c binder.c
	$(CC) $(OPTIONS) -o stub_downloader.o -c downloader.c

clean:
	rm -f binder.o stub_downloader.o